version: '3.7'

services:
  
  flask-base-redis:
    image: redis:latest
    container_name: flask-base-redis
    ports:
      - "6379:6379"
    networks:
      - flask-base-net        
    restart: always
    privileged: true
    tty: true  

  flask-base-postgres:
    image: postgres
    container_name: flask-base-postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    networks:
      - flask-base-net        
    restart: always
    privileged: true
    tty: true

  flask-base-pgadmin4:
    image: dpage/pgadmin4
    container_name: flask-base-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "16543:80"
    depends_on:
      - flask-base-postgres
    networks:
      - flask-base-net    
    links:
      - flask-base-postgres:db      
    restart: always
    privileged: true
    tty: true

  flask-base-sonarqube:
    image: sonarqube:8.3.1-community
    container_name: flask-base-sonarqube
    environment:
      - sonar.jdbc.username=postgres
      - sonar.jdbc.password=postgres
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonarqube
      - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
    user: "999"  
    ulimits:
      nofile:
       soft: 65536
       hard: 65536  
    ports:
      - "9000:9000"
    depends_on:
      - flask-base-postgres      
    networks:
      - flask-base-net    
    links:
      - flask-base-postgres:db         
    restart: always
    privileged: true
    tty: true

networks:
  flask-base-net:
    external: true