FROM python:3.7.9

MAINTAINER Luiz Dias <luizgtvgustavo@gmail.com>

ENV APP_HOME=/app

COPY . $APP_HOME

RUN pip install -U pip && pip install -r $APP_HOME/requirements.txt --upgrade

EXPOSE 8000

CMD flask db init
CMD flask db migrate
