"""empty message

Revision ID: 88903c57f2eb
Revises: 
Create Date: 2020-07-30 18:30:03.368636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88903c57f2eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blacklist_tokens', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'blacklist_tokens', type_='unique')
    # ### end Alembic commands ###
